version: '2'
services:
    redis:
        image: 'redis:3.2.7'

    mysql:
        image: mysql:latest
        ports:
            - "3307:3306"
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_USER=airflow
            - MYSQL_PASSWORD=airflow
            - MYSQL_DATABASE=airflow

    webserver:
        image: docker-airflow:mysql
        restart: always
        depends_on:
            - mysql
            - redis
        environment:
            # - LOAD_EX=n
            - FERNET_KEY=9IoTgQ_EJ0hCsamBU3Mctc7F9OkODnndOKCwkwXCAA
            - EXECUTOR=Celery
        # volumes:
        #     - /localpath/to/dags:/usr/local/airflow/dags
        ports:
            - "8080:8080"
        command: webserver

    flower:
        image: docker-airflow:mysql
        restart: always
        depends_on:
            - redis
        environment:
            - EXECUTOR=Celery
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        image: docker-airflow:mysql
        restart: always
        depends_on:
            - webserver
        # volumes:
        #     - /localpath/to/dags:/usr/local/airflow/dags
        environment:
            # - LOAD_EX=n
            - FERNET_KEY=9IoTgQ_EJ0hCsamBU3Mctc7F9OkODnndOKCwkwXCAA
            - EXECUTOR=Celery
        command: scheduler -n 5

    worker:
        image: docker-airflow:mysql
        restart: always
        depends_on:
            - scheduler
        # volumes:
        #     - /localpath/to/dags:/usr/local/airflow/dags
        environment:
            - FERNET_KEY=9IoTgQ_EJ0hCsamBU3Mctc7F9OkODnndOKCwkwXCAA
            - EXECUTOR=Celery
        command: worker
