version: '2'
services:
    mysql:
        image: mysql:latest
        ports:
            "3307:3306"
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_USER=airflow
            - MYSQL_PASSWORD=airflow
            - MYSQL_DATABASE=airflow

    webserver:
        image: docker-airflow:mysql
        restart: always
        depends_on:
            - mysql
        environment:
            # - LOAD_EX=n
            - EXECUTOR=Local
            - FERNET_KEY=9IoTgQ_EJ0hCsamBU3Mctc7F9OkODnndOKCwkwXCAA
        # volumes:
        #     - /localpath/to/dags:/usr/local/airflow/dags
        ports:
            - "8080:8080"
        command: webserver

    scheduler:
        image: docker-airflow:mysql
        restart: always
        depends_on:
            - webserver
        # volumes:
            # - ./requirements.txt:/requirements.txt:ro
            # - /localpath/to/dags:/usr/local/airflow/dags
        environment:
            # - LOAD_EX=n
            - FERNET_KEY=9IoTgQ_EJ0hCsamBU3Mctc7F9OkODnndOKCwkwXCAA
            - EXECUTOR=Local
        command: scheduler -n 5
